#!/usr/bin/env ruby

require 'open-uri'
require 'colorize'

def get_urls
  hacker_news = 'https://news.ycombinator.com'
  open(hacker_news)
    .read
    .split("a href=\"")
    .select {|x| x.start_with?("http")}
    .map { |x| x.split("\"").first }
    .select{ |x| !hacker_news.include? x }
    .select{ |x| !x.include?("ycombinator") }
end         

def fit(url)
  url
    .delete("https")
    .delete("http")
    .delete("://www.")
    .delete("://")
    .gsub("github", "github".green)
end

def fit_index(index)
  index.to_s.size == 1 ? "#{index} " : index.to_s
end

urls = get_urls

if /[^0-9]/.match(ARGV[0]).nil? && !ARGV[0].nil?
  urls = urls[0...ARGV[0].to_i]
end

def read(urls)
  urls.each_with_index do |url, i|
    puts "[#{fit_index(i).yellow}] #{fit(url)}"
  end

  print "[Enter:] "
  i = $stdin.gets.chomp.downcase
  abort if i == "q"
  read(urls) if i == ""
  system "open #{urls[i.to_i]}"
  read urls
end  

read urls
